In [1]:
import numpy as np
from sklearn.metrics import accuracy_score
y_pred = [0, 2, 1, 3]
y_true = [0, 1, 2, 3]
accuracy_score(y_true, y_pred)

0.5

In [2]:
accuracy_score(y_true, y_pred,normalize=False)

2

In [3]:
import pandas as pd
#create a simple dataset of people
data = {
    'Name' : ["শাহরিয়ার","আরাফাত","রায়হান", "সাকিব"],
    'Location' : ["রাজশাহী", "ঢাকা", "রংপুর", "বগুরা"],
    'Age' : [24,13,53,33]
}
frame = pd.DataFrame(data)
display(frame)

Name Location  Age
0  শাহরিয়ার  রাজশাহী   24
1    আরাফাত     ঢাকা   13
2    রায়হান    রংপুর   53
3     সাকিব    বগুরা   33

In [4]:
display(frame[frame.Age > 30])

Name Location  Age
2  রায়হান    রংপুর   53
3   সাকিব    বগুরা   33

In [5]:
import numpy as np
x = np.array([1,2,3])
x

array([1, 2, 3])

In [6]:
y = np.arange(10)
y

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
import numpy as np
#[[1 2 3 4]
#[5 6 7 8]
#[9 10 11 12]]
a = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [8]:
b = a[:2, 1 : 3]
c = a[:2]

print(c)
#[[1 2 3 4]
#[5 6 7 8]]
print(b)
#[[2 3]
#[6 7]]

[[1 2 3 4]
 [5 6 7 8]]
[[2 3]
 [6 7]]


In [9]:
def my_function():
    print("Hello from a function")
my_function()

Hello from a function


In [10]:
def double(x) :
    return x * 2
print(double(5))

10


In [11]:
tel = { "rafiq" : 4098,"mim": 4127}
print(tel)
tel["tafiq"] = 4217

tel["karim"] = 4217
print(tel)

{'rafiq': 4098, 'mim': 4127}
{'rafiq': 4098, 'mim': 4127, 'tafiq': 4217, 'karim': 4217}


In [12]:
mlbooks = {
    'data science from scratch' : 'joel grus','python data science hadnbook' : 'jake vanderplas' 
}
for k, v in mlbooks.items() :
    print(k,v)

data science from scratch joel grus
python data science hadnbook jake vanderplas


In [13]:
words = ['cat','window','defenestrate']
for w in words :
    print(w,len(w))

cat 3
window 6
defenestrate 12


In [14]:
square = [1, 4, 9, 16, 25]
square

[1, 4, 9, 16, 25]

In [15]:
square[0]

1

In [16]:
square[-1]

25

In [17]:
square[-2]

16

In [18]:
square[:]

[1, 4, 9, 16, 25]

In [19]:
square[:2]

[1, 4]

In [20]:
width = 20
height = 5 * 9
width * height

900

In [21]:
tax = 12.5 / 100
price = 100.50
price * tax

12.5625

In [22]:
price +_

113.0625

In [23]:
round(_,2)

113.06

In [24]:
round(_,1)

113.1

In [25]:
round(_,0)

113.0

In [26]:
round(_,)

113

In [27]:
#pass is just a placeholder for functionality to be added later
sequence = {'p','a','s','s'}
for val in sequence:
    pass
def function(args):
    pass
class example:
    pass

from sklearn import datasets
iris = datasets.load_iris()
dir(iris)